[package]
name = "macos_hardware_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
cocoa = "0.24"
objc = "0.2.7"
sysinfo = "0.29"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
log = "0.4"
env_logger = "0.11"